version: 2

sources:
  - name: dados_economicos
    database: voltaic-reducer-396401
    schema: dados_economicos
    tables:
      - name: indicadores
        description: "Dados brutos dos indicadores econômicos do BACEN"
        columns:
          - name: data
            description: "Data do indicador no formato DD/MM/YYYY"
          - name: valor
            description: "Valor do indicador"
          - name: indicador
            description: "Nome do indicador econômico"
          - name: serie
            description: "Código da série no BACEN"